config/routes.rb
NetworkOrganizr::Application.routes.draw do
  resources :devices

  resources :users

  resources :ipranges
  
  get 'hosts/dnsmasq' => 'devices#dnsmasq_hosts'
  get 'vpn/fritzbox' => 'devices#fritzbox_vpn'

   root 'devices#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	has_one :iprange, :through => :user
end

app/models/iprange.rb
class Iprange < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :devices
	belongs_to :iprange
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
  
  def dnsmasq_hosts
    @devices = Device.all
  end
  
  def fritzbox_vpn
    @devices = Device.where(:vpn => true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:manufacturer, :macaddresswifi, :macaddresslan, :group, :ip, :wifi, :vpn, :user_id)
    end
end

app/controllers/ip_ranges_controller.rb
class IpRangesController < ApplicationController
  before_action :set_ip_range, only: [:show, :edit, :update, :destroy]

  # GET /ip_ranges
  # GET /ip_ranges.json
  def index
    @ip_ranges = IpRange.all
  end

  # GET /ip_ranges/1
  # GET /ip_ranges/1.json
  def show
  end

  # GET /ip_ranges/new
  def new
    @ip_range = IpRange.new
  end

  # GET /ip_ranges/1/edit
  def edit
  end

  # POST /ip_ranges
  # POST /ip_ranges.json
  def create
    @ip_range = IpRange.new(ip_range_params)

    respond_to do |format|
      if @ip_range.save
        format.html { redirect_to @ip_range, notice: 'Ip range was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ip_range }
      else
        format.html { render action: 'new' }
        format.json { render json: @ip_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ip_ranges/1
  # PATCH/PUT /ip_ranges/1.json
  def update
    respond_to do |format|
      if @ip_range.update(ip_range_params)
        format.html { redirect_to @ip_range, notice: 'Ip range was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ip_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ip_ranges/1
  # DELETE /ip_ranges/1.json
  def destroy
    @ip_range.destroy
    respond_to do |format|
      format.html { redirect_to ip_ranges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip_range
      @ip_range = IpRange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_range_params
      params.require(:ip_range).permit(:name, :ipbase)
    end
end

app/controllers/ipranges_controller.rb
class IprangesController < ApplicationController
  before_action :set_iprange, only: [:show, :edit, :update, :destroy]

  # GET /ip_ranges
  # GET /ip_ranges.json
  def index
    @ipranges = Iprange.all
  end

  # GET /ip_ranges/1
  # GET /ip_ranges/1.json
  def show
  end

  # GET /ip_ranges/new
  def new
    @iprange = Iprange.new
  end

  # GET /ip_ranges/1/edit
  def edit
  end

  # POST /ip_ranges
  # POST /ip_ranges.json
  def create
    @iprange = Iprange.new(iprange_params)

    respond_to do |format|
      if @iprange.save
        format.html { redirect_to @iprange, notice: 'Ip range was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ip_range }
      else
        format.html { render action: 'new' }
        format.json { render json: @iprange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ip_ranges/1
  # PATCH/PUT /ip_ranges/1.json
  def update
    respond_to do |format|
      if @iprange.update(iprange_params)
        format.html { redirect_to @iprange, notice: 'Ip range was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @iprange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ip_ranges/1
  # DELETE /ip_ranges/1.json
  def destroy
    @iprange.destroy
    respond_to do |format|
      format.html { redirect_to ip_ranges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iprange
      @iprange = Iprange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iprange_params
      params.require(:iprange).permit(:name, :ipbase)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :iprange_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/ip_ranges_helper.rb
module IpRangesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :macaddresswifi %><br>
    <%= f.text_field :macaddresswifi %>
  </div>
  <div class="field">
    <%= f.label :macaddresslan %><br>
    <%= f.text_field :macaddresslan %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :vpn %><br>
    <%= f.check_box :vpn %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= collection_select(:device, :user_id, User.all, :id, :firstname) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/dnsmasq_hosts.text.erb
<% @devices.each do |device| %>
dhcp-host=<% unless device.macaddresswifi.blank? %><%= device.macaddresswifi.downcase %>,<% end %><% unless device.macaddresslan.blank? %><%= device.macaddresslan.downcase %>,<% end %><%= device.user.lastname.downcase %>-<%= device.user.firstname.downcase %>-<%= device.group.downcase %>-<%= device.manufacturer.downcase %>,<%= device.user.iprange.ipbase %><%= device.ip %>,12h
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/fritzbox_vpn.text.erb
<% @devices.each do |device| %>
vpncfg {
	connections { 
		enabled = yes;
		conn_type = conntype_user; 
		name = "<%= device.user.lastname.downcase %>-<%= device.user.firstname.downcase %>-<%= device.group.downcase %>-<%= device.manufacturer.downcase %>"; 
		always_renew = no; 
		reject_not_encrypted = no; 
		dont_filter_netbios = yes; 
		localip = 0.0.0.0; 
		local_virtualip = 0.0.0.0; 
		remoteip = 0.0.0.0; 
		remote_virtualip = <%= device.user.iprange.ipbase %>1<%= device.ip %>; 
		remoteid {
			key_id = "<%= device.user.lastname.downcase %>-<%= device.user.firstname.downcase %>-<%= device.group.downcase %>-<%= device.manufacturer.downcase %>";
		} 
		mode = phase1_mode_aggressive; 
		phase1ss = "all/all/all"; 
		keytype = connkeytype_pre_shared; 
		key = "<% if device.macaddresslan.blank? %><%= device.macaddresswifi.gsub(/:/,"").upcase %><% else %><%= device.macaddresslan.gsub(/:/,"").upcase %><% end %>"; 
		cert_do_server_auth = no; 
		use_nat_t = yes; 
		use_xauth = yes; 
		xauth {
			valid = yes; 
			username = "<%= device.user.lastname.downcase %>-<%= device.user.firstname.downcase %>-<%= device.group.downcase %>-<%= device.manufacturer.downcase %>"; 
			passwd = "<% if device.macaddresslan.blank? %><%= device.macaddresswifi.gsub(/:/,"").downcase %><% else %><%= device.macaddresslan.gsub(/:/,"").downcase %><% end %>";
		}
		use_cfgmode = yes; 
		phase2localid { 
			ipnet {
				ipaddr = 0.0.0.0; 
				mask = 0.0.0.0;
			} 
		}
		phase2remoteid {
			ipaddr = <%= device.user.iprange.ipbase %>1<%= device.ip %>; 
		}
		phase2ss = "esp-all-all/ah-none/comp-all/no-pfs";
		accesslist = "permit ip 10.10.0.0 255.255.240.0 <%= device.user.iprange.ipbase %>1<%= device.ip %> 255.255.255.255", 
			       "permit ip any <%= device.user.iprange.ipbase %>1<%= device.ip %> 255.255.255.255";
	}
	ike_forward_rules = "udp 0.0.0.0:500 0.0.0.0:500",
						"udp 0.0.0.0:4500 0.0.0.0:4500";
}
<% end %>

app/views/devices/index.html.erb
<div class="row">
	<h1>Devices</h1>
</div>

<div class="row">
<table class="table">
  <thead>
	<tr>
	  <th>Manufacturer</th>
	  <th>MAC-Address (WIFI)</th>
	  <th>MAC-Address (LAN)</th>
	  <th>Group</th>
	  <th>IP</th>
	  <th>VPN</th>
	  <th>User</th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>
  </thead>

  <tbody>
	<% @devices.each do |device| %>
	  <tr>
		<td><%= device.manufacturer %></td>
		<td><%= device.macaddresswifi %></td>
		<td><%= device.macaddresslan %></td>
		<td><%= device.group %></td>
		<td><%= device.user.iprange.ipbase %><%= device.ip %></td>
		<td><%= device.vpn %></td>
		<td><%= device.user.firstname %> <%= device.user.lastname %></td>
		<td><%= link_to 'Show', device %></td>
		<td><%= link_to 'Edit', edit_device_path(device) %></td>
		<td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>
</div>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacturer:</strong>
  <%= @device.manufacturer %>
</p>

<p>
  <strong>Macaddress:</strong>
  <%= @device.macaddresswifi %>
</p>

<p>
  <strong>Macaddress:</strong>
  <%= @device.macaddresslan %>
</p>

<p>
  <strong>Type:</strong>
  <%= @device.group %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @device.ip %>
</p>


<p>
  <strong>Vpn:</strong>
  <%= @device.vpn %>
</p>

<p>
  <strong>User:</strong>
  <%= @device.user_id %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/ip_ranges/_form.html.erb
<%= form_for(@ip_range) do |f| %>
  <% if @ip_range.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip_range.errors.count, "error") %> prohibited this ip_range from being saved:</h2>

      <ul>
      <% @ip_range.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ipbase %><br>
    <%= f.text_field :ipbase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ip_ranges/new.html.erb
<h1>New ip_range</h1>

<%= render 'form' %>

<%= link_to 'Back', ip_ranges_path %>

app/views/ipranges/_form.html.erb
<%= form_for(@iprange) do |f| %>
  <% if @iprange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iprange.errors.count, "error") %> prohibited this ip_range from being saved:</h2>

      <ul>
      <% @iprange.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ipbase %><br>
    <%= f.text_field :ipbase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ipranges/edit.html.erb
<h1>Editing ip_range</h1>

<%= render 'form' %>

<%= link_to 'Show', @iprange %> |
<%= link_to 'Back', ipranges_path %>

app/views/ipranges/index.html.erb
<div class="row">
	<h1>IP-Ranges</h1>
</div>

<div class="row">
	<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>IP-Base</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ipranges.each do |iprange| %>
      <tr>
        <td><%= iprange.name %></td>
        <td><%= iprange.ipbase %>0</td>
        <td><%= link_to 'Show', iprange %></td>
        <td><%= link_to 'Edit', edit_iprange_path(iprange) %></td>
        <td><%= link_to 'Destroy', iprange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New IP-Range', new_iprange_path %>

</div>

app/views/ipranges/new.html.erb
<h1>New ip_range</h1>

<%= render 'form' %>

<%= link_to 'Back', ipranges_path %>

app/views/ipranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @iprange.name %>
</p>

<p>
  <strong>Ipbase:</strong>
  <%= @iprange.ipbase %>
</p>

<%= link_to 'Edit', edit_iprange_path(@iprange) %> |
<%= link_to 'Back', ipranges_path %>

app/views/layouts/_footer.html.erb
&copy; <%= Time.now.year %> organizr by <a href="http://designstudio.sebastianbinder.com" target="_blank">designstudio.sebastian.binder</a> · <%#= link_to(t(".imprint"), :controller => "indices", :action => "imprint") %> · <%#= link_to(t(".privacy"), :controller => "indices", :action => "privacy") %> · <%#= link_to("Hilfe", manuals_path()) %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
	<li <% if params[:controller] == "devices" %>class="active"<% end %>><%= link_to("Devices", devices_path()) %></li>
	<li <% if params[:controller] == "users" %>class="active"<% end %>><%= link_to("Users", users_path()) %></li>
	<li <% if params[:controller] == "ipranges" %>class="active"<% end %>><%= link_to("IP-Ranges", ipranges_path()) %></li>
</ul>

app/views/layouts/_usercontrol.html copy.erb
<% if user_signed_in? %>
	<ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".language") %> <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><%= link_to t(".lang.english"), params.merge({:locale => 'en'}) %></li>
				<li><%= link_to t(".lang.german"), params.merge({:locale => 'de'}) %></li>
			</ul>
		</li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.firstname %> <%= current_user.lastname %> <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="<%= user_path(current_user) %>"><%= t('.my_profile') %></a></li>
				<li class="divider"></li>
				<li class="danger"><a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"><%= t('.logout') %></a></li>
			</ul>
		</li>
	</ul>
<% else %>
	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "navbar-form navbar-right"}) do |f| %>
		<div class="form-group">
			<%= f.text_field :email, :class => "form-control", placeholder: "#{t(".desc.email")}", size: 20  %>
		</div>
		<div class="form-group">
			<%= f.password_field :password, :class => "form-control", placeholder: "#{t(".desc.password")}", size: 20  %>
		</div>
		<% if devise_mapping.rememberable? %>
			<%= f.hidden_field :remember_me, :value => true %>
		<% end -%>
		<div class="btn-group">
			<button type="submit" class="btn btn-success"><%= t(".login") %></button>
		</div>
	<% end %>
	<ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".language") %> <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><%= link_to t(".lang.english"), params.merge({:locale => 'en'}) %></li>
				<li><%= link_to t(".lang.german"), params.merge({:locale => 'de'}) %></li>
			</ul>
		</li>
	</ul>
<% end %>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
	<head>
		<title>club.organizr - manage your club the organizr way!</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "club.organizr", root_path, class: "navbar-brand" %>
			</div>
			<div class="navbar-collapse collapse">
				<%= render "layouts/navigation" %>
				<%= render "layouts/usercontrol" %>
			</div>
		</nav>
		<div id="<%= params[:controller] %>-<%= params[:action] %>" class="container">
			<% unless notice.nil? %><div class="alert alert-success"><%= notice %></div><% end %>
			<% unless alert.nil? %><div class="alert alert-danger"><%= alert %></div><% end %>
			
			<%= yield %>

		</div>

		<footer class="modal-footer" role="contentinfo">
			<div class="container">
				<%= render "layouts/footer" %>
			</div>
		</footer>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetworkOrganizr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :iprange_id %><br>
    <%= collection_select(:user, :iprange_id, Iprange.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row">
	<h1>Users</h1>
</div>

<div class="row">
	<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>E-Mail</th>
      <th>IP-Range</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.iprange.name %> (<%= user.iprange.ipbase %>0)</td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Iprange:</strong>
  <%= @user.iprange.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>